### ISSUE TITLE
Acquiring the results

### ISSUE THREAD

**Issue by MariaMel98** [ekalinicheva/multi_layer_vegetation#2]
In case I want to acquire the results and the model for the given WildForest3D dataset, which file should I run and with what arguments? When I try to run main_DL.py it doesn't go past line 49 :  if os.path.exists(args.path_inference + "Placette_" + str(pl) + "/Pl_" + str(pl) + "_inference_data_clipped_xyzinr.ply"):
How can I acquire the inference data?

**Comment by ekalinicheva** [comment]
sorry, my bad, i've changed the config, main_DL and model_pointnet2 files, so it should work fine when you launch main_DL with all the right paths to the files in the configuration.

**Comment by MariaMel98** [comment]
Thank you for your response! I downloaded the updated file and when I run main_DL.py I get this error: 
File "/home/mariamlt/anaconda3/envs/my_env/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2251, in pdist
    return pdist_fn(X, out=out, **kwargs)
ValueError: Unsupported dtype object
I'm thinking if it might be an error because of the scipy package version. Could you tell me what scipy version do you use in order to use the same?

**Comment by ekalinicheva** [comment]
Hello! Have you also updated two other files?
scipy 1.5.4
Also I use Python 3.7 and not 3.8.

**Comment by MariaMel98** [comment]
Yes I downloaded the whole zip again. Ok maybe I will try python 3.7 then, thanks!

**Comment by MariaMel98** [comment]
I'm sorry for bugging you again but are you sure you have uploaded a changed version of the model_pointnet2  file?
![Στιγμιότυπο οθόνης (76)](https://user-images.githubusercontent.com/105556892/180458557-3e257e9c-3a2d-4966-a6d7-4a76bad766bb.png)
  The comment  is the only change?

**Comment by ekalinicheva** [comment]
yes, i've only changes sa1, sa2 and sa3

**Comment by MariaMel98** [comment]
I tried python 3.7 and scipy version 1.5.4 and the ValueError: Unsupported dtype object disappeared.
