### ISSUE TITLE
Type error in point_cloud_classifier.py

### ISSUE THREAD

**Issue by MariaMel98** [ekalinicheva/multi_layer_vegetation#3]
![Στιγμιότυπο οθόνης (77)](https://user-images.githubusercontent.com/105556892/180800197-bf76ed86-686d-4573-9bb7-bc3c493531b5.png)

After I run python main_DL.py some files are  generated (such as saved data folder, results folder, stats.txt) and then i get this type error and I don't know how to fix it. 
Did anybody face the same error?

**Comment by ekalinicheva** [comment]
not sure if it helps, but maybe precise n_neighbors=1 or k=1 instead of just NearestNeighbours(1, ...). maybe the problem is related to the scikit version.

**Comment by MariaMel98** [comment]
I changed it to n_neighbors = 1 as you suggested and it worked!
