### ISSUE TITLE
Acquiring the ground truth

### ISSUE THREAD

**Issue by MariaMel98** [ekalinicheva/multi_layer_vegetation#4]
Hello! I would like to ask if I can see the ground truth for the point clouds of the placcettes in order to see how close are the results. In the **data_point_clouds** folder  the ply files are appearing without annotations for the 6 different classes and these annotations exist in the corresponding csv files. Is there a script in the code which I can use to annotate the initial point cloud (I'm talking about the files named **Pl_XX_final_data_xyzinr.ply**) ? 

i found this instuction line in the ReadMe file but I'm not sure what does it mean..Any help would be great!

![Στιγμιότυπο οθόνης (86)](https://user-images.githubusercontent.com/105556892/186849375-a6274bcb-fe6a-4504-898b-cea0ab15bdee.png)

**Comment by ekalinicheva** [comment]
Hello. You can generate the ground truth as a separate file by using _utils/generate_dataset.py_ (which uses _open_ply_all_ function). Otherwise, when the final ply file with the results is created, there is also a "gt" column there.
I will modify the readme to clarify this.

**Comment by MariaMel98** [comment]
Thank you for your response! I saw the"gt" column in the final files. For the "error"column how do you calculate it? Also, is there a way to see the results you produce with your code? I want to be sure that I also produce the same results that's why I'm asking.  Thanks again for your help!

**Comment by ekalinicheva** [comment]
Hello. At my opinion, the error column is not that much informative. You can customize it in "utils/useful_functions.py" for your own purposes. 
 The results produced by the algorithm are never exactly the same due to the nature of NN. You have the GT for the point clouds and GT for the occupancy maps, the rest is for you to interpret, because my results can not be considered as the "ideal ones".

**Comment by MariaMel98** [comment]
Ok thank you again, I'm closing the issue here.

**Comment by MariaMel98** [comment]
A final question about the datasest. As i saw from the **gt** column in the classified point clouds, you assign the value **255** to coniferous right? If this is correct why there are coniferous points on the ground? The screenshot is the **ground truth** of **Placette 15**, for reference.
![PL_15_GT](https://user-images.githubusercontent.com/105556892/189364771-4017e49b-528c-4e90-bfa0-05043790d384.png)

**Comment by ekalinicheva** [comment]
no, 255 is nodata. It is set as -1 in the code, but is read as 255 when you open the file for visualisation. annotated coniferous should have value 4.

**Comment by MariaMel98** [comment]
oh ok my bad. So they are points that we don't know their ground truth, right?

**Comment by ekalinicheva** [comment]
yep.
