### ISSUE TITLE
Watertight meshes

### ISSUE THREAD

**Issue by MariaMel98** [ekalinicheva/multi_layer_vegetation#5]
This is not an issue, it's more like some question I have for some scripts..

Is it possible to produce the watertight meshes that you refer to in the paper from the code? I'm running **create_mesh_and_rasters.py** and **create_mesh_new.py** and the results are the final 2D coverage rasters and then some point clouds which are seperate for the different layers of the vegetation. Shouldn't the code also produce the watertight mesh?

And another question, for the **create_different_results.py** script. When I try to run it I get the error    **/home/DATASETS/sites_placettes/sites100m_EPSG2154.tif: No such file or directory**, which is expected because in the DATASETS folder there is no folder named sites_placettes. I wanted to ask you what is this folder and when should it have been created?

**Comment by ekalinicheva** [comment]
hello. 
1/ those point clouds are the meshes produced for each layer. you are probably using the wrong app to visualise your results. you can use Cloud Compare, for example. i've changed a couple of lines in the code, so it produces a single mesh for all the layers in one file.

2/my bad, this file for made for the inference data. I changed it, so it works for the test results now.

**Comment by MariaMel98** [comment]
I am using meshlab for the visualization, I see the point cloud meshes for each layer, but I had misunderstood the readme and I thought that the code could produce a solid mesh.
